name: Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: ${{ success() }}

      - name: executing remote ssh commands using password
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            mkdir -p deployed/current
            mkdir -p deployed/shared/boltcms
            mkdir -p deployed/shared/boltcms/public/files

      - name: Deploy to host
        if: ${{ success() }}
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: ./boltcms/
          remote_path: ${{ secrets.REMOTE_TARGET }}/deployed/current
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: symlink folders
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        env:
          TARGET_FOLDER: ${{ secrets.REMOTE_TARGET }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script_stop: true
          script: |
            rm -f public_html
            rm -f ~/deployed/current/public/files
            ln -sf ~/deployed/shared/boltcms/.env ~/deployed/current/.env
            ln -sf ~/deployed/shared/boltcms/public/files ~/deployed/current/public/files
            ln -sf ~/deployed/current/public public_html

      - name: running composer install
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ~/deployed/current
            composer install --prefer-dist --no-progress --no-scripts
            composer dumpauto
