name: Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          cd boltcms
          composer install --prefer-dist --no-progress --no-scripts

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
        if: ${{ success() }}

      - name: executing remote ssh commands using password
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            mkdir -p deployed/current
            mkdir -p deployed/shared/boltcms
            mkdir -p deployed/shared/boltcms/public/files

      - name: Deploy to host
        if: ${{ success() }}
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: ./boltcms/
          remote_path: ${{ secrets.REMOTE_TARGET }}/deployed/current
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: symlink folders
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script_stop: true
          script: |
            ln -sf deployed/shared/boltcms/.env current/.env
            ln -sf deployed/shared/boltcms/public/files current/files
            ln -sf deployed/current/public public_html